version: '3.8'

services:
  neuraflex-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: neuraflex-moe-api
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
      - ../logs:/app/logs
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/app/models/neuraflex-7b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
